import { complex as c, cequal, minv, mmul, type CMat } from './math/math'
import type { UrlState } from './urlState'

export interface Example extends UrlState {
  name: string
}

const s3 = Math.sqrt(3) / 2

function example(name: string, depth: number, [a, b]: [CMat, CMat]): Example {
  return { name, depth, matrices: [a, b], showIso: [true, true] }
}

// The icosahedral rotation group A₅, generated by s and u in SU(2) with
// s⁵ = u³ = (su)² = -I. SU(2) fixes the origin, so conjugate by a translation
// moving the origin a distance 1 towards the boundary point ip. The orbit of
// the origin is then a rhombicosidodecahedron; p is chosen so that the s-edges
// (pentagons) and u-edges (triangles) have equal length.
function icosahedral(): [CMat, CMat] {
  const t = Math.PI / 5
  const y = 1 / (2 * Math.tan(t))
  const x = Math.sqrt(0.75 - y * y)
  const s: CMat = [c(Math.cos(t), Math.sin(t)), c(0), c(0), c(Math.cos(t), -Math.sin(t))]
  const u: CMat = [c(0.5, y), c(x), c(-x), c(0.5, -y)]

  const p = 0.19793977394217
  const n = Math.sqrt(1 + p * p)
  const e = Math.exp(1 / 2)
  // rot fixes the origin and maps ∞ to ip.
  const rot: CMat = [c(0, p / n), c(-1 / n), c(1 / n), c(0, -p / n)]
  const translate = mmul(mmul(rot, [c(1 / e), c(0), c(0), c(e)]), minv(rot))
  // Round off float noise so entries like -0.00i don't show in the inputs.
  const round = (x: number) => +x.toFixed(12) + 0
  const conj = (m: CMat) => mmul(mmul(translate, m), minv(translate))
    .map(z => c(round(z.re), round(z.im))) as CMat
  return [conj(s), conj(u)]
}

export const examples: Example[] = [
  // Pairs the circles of radius 1.25 centred at ±2 and at ±2i.
  example('Schottky group', 10, [
    [c(1.6), c(1.95), c(0.8), c(1.6)],
    [c(0, 1.6), c(-4.45), c(0.8), c(0, 1.6)],
  ]),
  // Free, Fuchsian; ⟨a, b⟩ = Γ(2) in PSL(2, ℤ).
  example('Sanov subgroup', 10, [
    [c(1), c(2), c(0), c(1)],
    [c(1), c(0), c(2), c(1)],
  ]),
  // Commutator subgroup of PSL(2, ℤ); [a, b] is parabolic.
  example('Punctured torus group', 10, [
    [c(1), c(1), c(1), c(2)],
    [c(1), c(-1), c(-1), c(2)],
  ]),
  // Indra's Pearls: Grandma's recipe with t_a = t_b = 2.
  example('Apollonian gasket', 10, [
    [c(1), c(0), c(0, -2), c(1)],
    [c(1, -1), c(1), c(1), c(1, 1)],
  ]),
  // Riley's representation, with ρ a root of ρ² - ρ + 1.
  example('Figure-eight knot group', 10, [
    [c(1), c(1), c(0), c(1)],
    [c(1), c(0), c(0.5, -s3), c(1)],
  ]),
  // Commuting parabolics: the orbit lies on a horosphere.
  example('Parabolic ℤ²', 10, [
    [c(1), c(1), c(0), c(1)],
    [c(1), c(0, 1), c(0), c(1)],
  ]),
  example('Icosahedral group', 8, icosahedral()),
]

// An example matches if it shows the same isometries; depth is ignored.
export function matchesExample(ex: Example, state: Pick<UrlState, 'matrices' | 'showIso'>) {
  return [0, 1].every(i =>
    ex.showIso[i] === state.showIso[i] &&
    ex.matrices[i].every((z, j) => cequal(z, state.matrices[i][j]))
  )
}
